services:
  nginx:
    image: nginx:1.23.3-alpine
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./conf.d:/etc/nginx/conf.d/default.conf
    networks:
      - backend

  php:
    depends_on:
      - nginx
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /var/www/html
    restart: always
    ports:
      - "9000:80"
    volumes:
      - ./:/var/www/html
    networks:
      - backend

networks:
  backend: {}